[ABOUT]
NAME = ApexLap Uploader
AUTHOR = alejandrorodm
VERSION = 1.0
DESCRIPTION = Sube automáticamente tus vueltas limpias de Assetto Corsa a tu liga de ApexLap.

; App en Lua de Custom Shaders Patch (CSP). El fichero de script es
; ApexLapUploader.lua y la ventana llama a la función script.windowMain.
[CORE]
LAZY = ApexLapUploader

[WINDOW_0]
ID = main
NAME = ApexLap
FUNCTION_MAIN = windowMain
SIZE = 360, 460
RESIZABLE = 1
